on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: 'action'
        run: pwd

      - uses: actions/checkout@v3

      - name: "login"
        run: docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }}
      - name: "build"
        run: docker build -t ${{ secrets.DOCKER_USER }}/myimage .
      - name: "push d"
        run: docker push ${{ secrets.DOCKER_USER }}/myimage


